# Generated by Django 2.1.7 on 2019-06-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='waiting',
            field=models.PositiveIntegerField(default=0, verbose_name='正在等待的人数'),
        ),
    ]
