# Generated by Django 2.1.7 on 2019-06-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_station_waiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wj',
            name='q6',
        ),
    ]
